### PR TITLE
fix-mrcv: pointed AWS COSE repository to our fork

### PR DESCRIPTION
**Pull request by dominic-mulligan-arm**

### CODE REVIEW

**Review by gbryant-arm — DISMISSED** [review]
LGTM

**Comment by dominic-mulligan-arm** [comment]
Will wait for @dreemkiller's approval before merge.

**Comment by dreemkiller** [comment]
Could we not have modified this `Cargo.toml` file with:
```
serde_with = { version = "=1.9.4", default_features = false }
```
instead of forking the direct dependency?

**Comment by dominic-mulligan-arm** [comment]
Does that pin all dependencies on `serde_with` transitively in the dependency tree?  I didn't think it did, hence why I forked.  I'll take a look...

**Comment by dreemkiller** [comment]
I **think** it does, but it bears scrutiny. If it does work, I would prefer that to forking and maintaining a dependency.

**Comment by dominic-mulligan-arm** [comment]
You're right, `cargo tree` shows the dependency being correctly overridden.  I've updated this PR to pin the dependency, and will delete the fork.

**Review by dreemkiller — DISMISSED** [review]

**Comment by dominic-mulligan-arm** [comment]
+1 reached, merging.

**Comment by dominic-mulligan-arm** [comment]
Sorry @dreemkiller can you approve again?  I signed the commits with the wrong key...

**Review by dreemkiller — APPROVED** [review]

**Pull request merged**
